### ISSUE TITLE
[使用问题] 更新v1.1.1后，实体都变得不可用

### ISSUE THREAD

**Issue by lxz946786639** [CubicPill/china_southern_power_grid_stat#12]
更新最新版本后，实体都不可用了，把集成删除，再重新添加，再添加电费帐号都是如此

**Comment by lxz946786639** [comment]
![image](https://github.com/CubicPill/china_southern_power_grid_stat/assets/40382425/5bc836d9-3e5a-4d1c-b365-7feedc9b5202)

**Comment by xiaoyv404** [comment]
same

**Comment by CubicPill** [comment]
请提供一下相关日志（ha网页内可以查看），注意隐去错误信息

**Comment by xiaoyv404** [comment]
```
此错误来自自定义集成。

Logger: custom_components.china_southern_power_grid_stat.sensor
Source: custom_components/china_southern_power_grid_stat/sensor.py:568
Integration: China Southern Power Grid Statistics (documentation, issues)
First occurred: 19:07:27 (3 occurrences)
Last logged: 19:11:49

Unexpected error fetching CSG Account 15015066106 data: string indices must be integers
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/china_southern_power_grid_stat/sensor.py", line 937, in _async_update_data
    await self._async_update_account_data(account)
  File "/config/custom_components/china_southern_power_grid_stat/sensor.py", line 905, in _async_update_account_data
    await asyncio.gather(
  File "/config/custom_components/china_southern_power_grid_stat/sensor.py", line 657, in _async_update_this_month_stats_and_ladder
    this_month_by_day, this_month_kwh = self.merge_by_day_data(
  File "/config/custom_components/china_southern_power_grid_stat/sensor.py", line 568, in merge_by_day_data
    by_day[idx][WF_ATTR_CHARGE] = item[WF_ATTR_CHARGE]
TypeError: string indices must be integers

```

**Comment by xiaoyv404** [comment]
还有一个是 `深圳电费日历查询返回:营销接口异常：营销系统：10001-服务调用异常,执行数据库查询出错!`
我还在看里面是否有敏感信息

**Comment by CubicPill** [comment]
> ```
> Logger: custom_components.china_southern_power_grid_stat.sensor
> Source: custom_components/china_southern_power_grid_stat/sensor.py:402
> Integration: China Southern Power Grid Statistics ([documentation](https://github.com/CubicPill/china_southern_power_grid_stat/), [issues](https://github.com/CubicPill/china_southern_power_grid_stat/issues))
> First occurred: 19:07:27 (6 occurrences)
> Last logged: 19:11:49
> 
>     Error fetching data in coordinator: API error, function get_month_daily_cost_detail, <CSGAPIError sta=02 message=深圳电费日历查询返回:营销接口异常：营销系统：10001-服务调用异常,执行数据库查询出错!查询语句：
> ```
> 
> 甚至还把数据库查询语句爆出来了（） 过于离谱

是这样的，我一开始写这个集成的时候经常会返回这个错误，最近才好，这个请求一般要卡十几秒才会完成。

上面那个错误应该是没处理好接口请求失败的情况，我这就写个patch出来

**Comment by lxz946786639** [comment]
> 

今天可以处理好吗😀

**Comment by CubicPill** [comment]
打开HACS，选择本集成，右边三个点选择"Redownload"，然后打开"Show beta versions"这个选项，下载v1.1.2-beta版本看看有没有解决。（完事记得把这个选项重新关掉）

**Comment by xiaoyv404** [comment]
我这边运行正常

**Comment by lxz946786639** [comment]
![image](https://github.com/CubicPill/china_southern_power_grid_stat/assets/40382425/8830f338-adbe-4fec-9059-882d22adec58)
更新后，只有部分有值，其它状态都是未知

**Comment by lxz946786639** [comment]
> 我这边运行正常

请问你是如何操作的？

**Comment by xiaoyv404** [comment]
> ![image](https://github.com/CubicPill/china_southern_power_grid_stat/assets/40382425/8830f338-adbe-4fec-9059-882d22adec58)
> 更新后，只有部分有值，其它状态都是未知

啊，我以为是我这边的问题，所以就没提这个，第一次用这个东西。

**Comment by lxz946786639** [comment]
> > ![image](https://user-images.githubusercontent.com/40382425/239714772-8830f338-adbe-4fec-9059-882d22adec58.png)
> > 更新后，只有部分有值，其它状态都是未知
> 
> 啊，我以为是我这边的问题，所以就没提这个，第一次用这个东西。

上一个版本，这些都明数据的噢

**Comment by CubicPill** [comment]
麻烦再提供一下相关日志吧，应该会有warning的

**Comment by xiaoyv404** [comment]
好的，请稍等

> 麻烦再提供一下相关日志吧，应该会有warning的

**Comment by xiaoyv404** [comment]
```
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:583
Integration: 传感器 (documentation, issues)
First occurred: 13:31:06 (1 occurrences)
Last logged: 13:31:06

Error while setting up china_southern_power_grid_stat platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: 'unknown'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/china_southern_power_grid_stat/sensor.py", line 200, in async_setup_entry
    await coordinator.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 237, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 349, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 146, in async_update_listeners
    update_callback()
  File "/config/custom_components/china_southern_power_grid_stat/sensor.py", line 306, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.0302000232033393_latest_day_cost has device class monetary, state class total unit CNY and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>)
```

```
此错误来自自定义集成。

Logger: custom_components.china_southern_power_grid_stat.sensor
Source: custom_components/china_southern_power_grid_stat/sensor.py:402
Integration: China Southern Power Grid Statistics (documentation, issues)
First occurred: 13:31:06 (2 occurrences)
Last logged: 13:31:06

Error fetching data in coordinator: API error, function get_month_daily_cost_detail, <CSGAPIError sta=02 message=深圳电费日历查询返回:营销接口异常：营销系统：10001-服务调用异常,执行数据库查询出错!查询语句：
```

**Comment by lxz946786639** [comment]
短期可以修复得好吗？或者说，我们回退到v1.1.0版本

**Comment by sd1218487** [comment]
我也是同样的问题，我也以为是我的问题

**Comment by lxz946786639** [comment]
我已回退到1.0.3版本，目前可以正常使用。实体少了几个但够用，期待新版本问题尽快修复，谢谢

**Comment by CubicPill** [comment]
请看最新beta release，看看是否修复

**Comment by lxz946786639** [comment]
![image](https://github.com/CubicPill/china_southern_power_grid_stat/assets/40382425/b70099eb-a7cf-4c10-88f8-faed1af9acb6)
最新的bate版本，阶梯电价相关信息，本月、上月、最近电费 都是未知

**Comment by lxz946786639** [comment]
> 请看最新beta release，看看是否修复

最新的bate版本，阶梯电价相关信息，本月、上月、最近电费 都是未知。不过现有数据也够我用了，哈哈

**Comment by sd1218487** [comment]
> 请看最新beta release，看看是否修复

可以了，最新的Beta可以修复了

**Comment by lxz946786639** [comment]
> > > 请看最新beta release，看看是否修复
> > 
> > 
> > 最新的bate版本，阶梯电价相关信息，本月、上月、最近电费 都是未知。不过现有数据也够我用了，哈哈
> 
> 这个可能就是接口的问题了，暂时没办法😂

好的，问题不大。我平时也不看这些东西😂
