### ISSUE TITLE
无法获取信息

### ISSUE THREAD

**Issue by fangguisheng** [CubicPill/china_southern_power_grid_stat#4]
此错误来自自定义集成。

Logger: custom_components.china_southern_power_grid_stat.sensor
Source: helpers/update_coordinator.py:182
Integration: China Southern Power Grid Statistics (documentation, issues)
First occurred: 12:45:52 (1 occurrences)
Last logged: 12:45:52

Error fetching CSG Account 15600000002 data: Error communicating with API: <CSGAPIError sta=99999 message=None>

Logger: homeassistant.components.sensor
Source: custom_components/china_southern_power_grid_stat/sensor.py:200
Integration: 传感器 (documentation, issues)
First occurred: 12:45:52 (1 occurrences)
Last logged: 12:45:52

Error while setting up china_southern_power_grid_stat platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/china_southern_power_grid_stat/sensor.py", line 145, in async_setup_entry
    await coordinator.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/config/custom_components/china_southern_power_grid_stat/sensor.py", line 200, in _handle_coordinator_update
    account_data = self._coordinator.data.get(self._account_number)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by CubicPill** [comment]
应该是更新过程中某个API更新失败，错误没有处理好造成的bug，正在修复

**Comment by CubicPill** [comment]
请尝试手动clone并安装：[#0071712](https://github.com/CubicPill/china_southern_power_grid_stat/tree/0071712192c996ea333954af21e51bad3369dead)

**Comment by CubicPill** [comment]
Fixed in [#0071712](https://github.com/CubicPill/china_southern_power_grid_stat/tree/0071712192c996ea333954af21e51bad3369dead)
